### ISSUE TITLE
download_from_catalog -h command not working

### ISSUE THREAD

**Issue by rmania** [Amsterdam/data-processing#9]
```download_from_catalog -h``` 
vanaf de CLI werkt niet. Foutmelding:

```
Traceback (most recent call last):
  File "/home/diederik/anaconda3/bin/download_from_catalog", line 11, in <module>
    sys.exit(main())
  File "/home/diederik/anaconda3/lib/python3.6/site-packages/datapunt_processing/extract/download_from_catalog.py", line 101, in main
    args = parser().parse_args()
  File "/home/diederik/anaconda3/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/diederik/anaconda3/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/diederik/anaconda3/lib/python3.6/argparse.py", line 1968, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/diederik/anaconda3/lib/python3.6/argparse.py", line 1908, in consume_optional
    take_action(action, args, option_string)
  File "/home/diederik/anaconda3/lib/python3.6/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/diederik/anaconda3/lib/python3.6/argparse.py", line 1020, in __call__
    parser.print_help()
  File "/home/diederik/anaconda3/lib/python3.6/argparse.py", line 2362, in print_help
    self._print_message(self.format_help(), file)
  File "/home/diederik/anaconda3/lib/python3.6/argparse.py", line 2346, in format_help
    return formatter.format_help()
  File "/home/diederik/anaconda3/lib/python3.6/argparse.py", line 282, in format_help
    help = self._root_section.format_help()
  File "/home/diederik/anaconda3/lib/python3.6/argparse.py", line 213, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/home/diederik/anaconda3/lib/python3.6/argparse.py", line 213, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/home/diederik/anaconda3/lib/python3.6/argparse.py", line 213, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/home/diederik/anaconda3/lib/python3.6/argparse.py", line 213, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/home/diederik/anaconda3/lib/python3.6/argparse.py", line 519, in _format_action
    help_text = self._expand_help(action)
  File "/home/diederik/anaconda3/lib/python3.6/argparse.py", line 606, in _expand_help
    return self._get_help_string(action) % params
TypeError: must be real number, not dict
```

**Comment by Lytrix** [comment]
Fixed using the default option:
https://github.com/Amsterdam/data-processing/blob/master/src/datapunt_processing/extract/download_from_catalog.py#L98
argparse does not like url encoding in the help file.
